services:
  - name: rails-backend
    type: web
    runtime: ruby
    repo: https://github.com/wyu6609/BOT_IO
    rootDir: ./
    plan: free # or use 'starter'
    buildCommand: |
      bundle install
      rails db:migrate
      rails db:seed # Add this line to seed the database
      rails assets:precompile
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-service-name
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false # Ensure this is manually set in the environment

  - name: react-frontend
    type: static_site
    repo: https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO
    rootDir: client/
    buildCommand: npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://rails-backend.onrender.com
